const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILED: 'FETCH_ALL_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
    FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED',

    FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
    FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED',

    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',

    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAILED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAILED',


    //product
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILED: 'CREATE_PRODUCT_FAILED',

    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',

    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
    EDIT_PRODUCT_FAILED: 'EDIT_PRODUCT_FAILED',

    FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',
    FETCH_ALL_PRODUCT_FAILED: 'FETCH_ALL_PRODUCT_FAILED',

    FETCH_ALL_LIST_PRODUCT_SUCCESS: 'FETCH_ALL_LIST_PRODUCT_SUCCESS',
    FETCH_ALL_LIST_PRODUCT_FAILED: 'FETCH_ALL_LIST_PRODUCT_FAILED',

    BUY_PRODUCT_SUCCESS: 'BUY_PRODUCT_SUCCESS',
    BUY_PRODUCT_FAILED: 'BUY_PRODUCT_FAILED',

    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',

    //category
    CREATE_PRODUCT_CATEGORY_SUCCESS: 'CREATE_PRODUCT_CATEGORY_SUCCESS',
    CREATE_PRODUCT_CATEGORY_FAILED: 'CREATE_PRODUCT_CATEGORY_FAILED',

    DELETE_PRODUCT_CATEGORY_SUCCESS: 'DELETE_PRODUCT_CATEGORY_SUCCESS',
    DELETE_PRODUCT_CATEGORY_FAILED: 'DELETE_PRODUCT_CATEGORY_FAILED',

    EDIT_PRODUCT_CATEGORY_SUCCESS: 'EDIT_PRODUCT_CATEGORY_SUCCESS',
    EDIT_PRODUCT_CATEGORY_FAILED: 'EDIT_PRODUCT_CATEGORY_FAILED',

    FETCH_ALL_CATEGORY_SUCCESS: 'FETCH_ALL_CATEGORY_SUCCESS',
    FETCH_ALL_CATEGORY_FAILED: 'FETCH_ALL_CATEGORY_FAILED',

    //Type of product
    CREATE_PRODUCT_TYPE_SUCCESS: 'CREATE_PRODUCT_TYPE_SUCCESS',
    CREATE_PRODUCT_TYPE_FAILED: 'CREATE_PRODUCT_TYPE_FAILED',

    DELETE_PRODUCT_TYPE_SUCCESS: 'DELETE_PRODUCT_TYPE_SUCCESS',
    DELETE_PRODUCT_TYPE_FAILED: 'DELETE_PRODUCT_TYPE_FAILED',

    EDIT_PRODUCT_TYPE_SUCCESS: 'EDIT_PRODUCT_TYPE_SUCCESS',
    EDIT_PRODUCT_TYPE_FAILED: 'EDIT_PRODUCT_TYPE_FAILED',

    FETCH_ALL_PRODUCT_TYPE_SUCCESS: 'FETCH_ALL_PRODUCT_TYPE_SUCCESS',
    FETCH_ALL_PRODUCT_TYPE_FAILED: 'FETCH_ALL_PRODUCT_TYPE_SUCCESS',

})

export default actionTypes;